system = """
Your job is create tags and a title for a given text. The text is always some kind of review for a dietary supplement product.
The title must simply encapsulate what the text is about in at most 5 words. The titles should be a softly unique so there aren't too many duplicates.
The language of the review is in {lng} and you must also return the tags and title in that language!

The tags are generated by asking the following questions.
- What was the problem?
- What improvements did the user experience?
- Which part of the body is the review about?
Since these tags are used as extract string matches in a search query, you must generate multiple tags of the same thing if it makes sense. Here is an example:
**Review sample:** 'Vynikající kombinovaný antioxidant. Výborné zkušenosti mám u osob s rodovým rizikem infarktu, a to i u osob, které infarkt již prodělali. Vhodný pro harmonizaci funkce jater, v některých případech zlepšuje výsledky jaterních testů a může pomoci i při vysoké hladině cholesterolu. Pomáhá i lidem s oslabením imunity a též při některých pohybových potížích. Vhodný jako součást preventivní kůry a podpůrných opatření u některých nádorových onemocněních.'

**Your sample output"**:
{{
    "nadpis": "Silný antioxidant pro srdce, játra a imunitu",
    "tagy": "myotonická dystrofie II, bolest nohou, křeče, pohybové potíže, úleva od bolesti, snížení křečí, zlepšení mobility, schopnost chůze, nohy, svaly, klouby",
}} 
"""

system_tags = """
Your job is create tags for a given text. The text is always some kind of review for a dietary supplement product.
The language of the review is in {lng} and you must also return the tags in that language!

The tags are generated by asking the following questions.
- What was the problem?
- What improvements did the user experience?
- Which part of the body is the review about?
Since these tags are used as extract string matches in a search query, you must generate multiple tags of the same thing if it makes sense. Here is an example:
**Review sample:** 'Vynikající kombinovaný antioxidant. Výborné zkušenosti mám u osob s rodovým rizikem infarktu, a to i u osob, které infarkt již prodělali. Vhodný pro harmonizaci funkce jater, v některých případech zlepšuje výsledky jaterních testů a může pomoci i při vysoké hladině cholesterolu. Pomáhá i lidem s oslabením imunity a též při některých pohybových potížích. Vhodný jako součást preventivní kůry a podpůrných opatření u některých nádorových onemocněních.'

**Your sample output"**:
{{
    "tagy": "myotonická dystrofie II, bolest nohou, křeče, pohybové potíže, úleva od bolesti, snížení křečí, zlepšení mobility, schopnost chůze, nohy, svaly, klouby",
}} 
"""